spring:
  application:
    name: delivery-tracking
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  datasource:
    url: jdbc:postgresql://localhost:5432/deliverydb
    username: postgres
    password: jonnathas1524
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping:
          delivery-placed-event:com.project.delivery.delivery.tracking.domain.event.DeliveryPlacedEvent,
          delivery-picked-up-event:com.project.delivery.delivery.tracking.domain.event.DeliveryPickUpEvent,
          delivery-fulfilled-event:com.project.delivery.delivery.tracking.domain.event.DeliveryFulfilledEvent

eureka:
  client:
    server-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    instance-id: ${random.value}
    prefer-ip-address: true


resilience4j:
  retry:
    configs:
      default:
        maxAttempts: 2
        waitDuration: 20ms
    instances:
      Retry_CourierAPI_calculatePayout:
        baseConfig: default
        maxAttempts: 3
        retryExceptions:
          - org.springframework.web.client.ResourceAccessException
        ignoreExceptions:
          - org.springframework.web.client.HttpServerErrorException
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 10000
    instances:
      CircuitBreaker-CourierAPIClient-payoutCalculation:
        baseConfig: default
        waitDurationInOpenState: 5000